export const emptyPlaylist = {
  owner: {
    uid: 0,
    login: "",
    name: "",
    verified: false,
    sex: "",
  },
  playlistUuid: "",
  available: false,
  uid: 0,
  kind: 0,
  title: "",
  revision: 0,
  snapshot: 0,
  trackCount: 0,
  visibility: "",
  collective: false,
  created: "",
  modified: "",
  isBanner: false,
  isPremiere: false,
  durationMs: 0,
  cover: { error: "", type: "", itemsUri: [], custom: false },
  ogImage: "",
  tags: [],
  prerolls: [],
  lastOwnerPlaylists: [],
  tracks: [],
};
